<?php

/**
 * @file
 * Bootstrap4 theme file.
 */

use Drupal\Component\Serialization\Yaml;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_preprocess_HOOK() for menu-local-tasks templates.
 *
 * Use preprocess hook to set #attached to child elements
 * because they will be processed by Twig and drupal_render will
 * be invoked.
 */
function vesta_bootstrap4_preprocess_menu_local_tasks(&$variables) {
  if (!empty($variables['primary'])) {
    $variables['primary']['#attached'] = [
      'library' => [
        'vesta_bootstrap4/drupal.nav-tabs',
      ],
    ];
  }
  elseif (!empty($variables['secondary'])) {
    $variables['secondary']['#attached'] = [
      'library' => [
        'vesta_bootstrap4/drupal.nav-tabs',
      ],
    ];
  }

  foreach (Element::children($variables['primary']) as $key) {
    $variables['primary'][$key]['#level'] = 'primary';
  }
  foreach (Element::children($variables['secondary']) as $key) {
    $variables['secondary'][$key]['#level'] = 'secondary';
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu-local-task templates.
 */
function vesta_bootstrap4_preprocess_menu_local_task(&$variables) {
  // Ensure is-active class is set when the tab is active. The generic active
  // link handler applies stricter comparison rules than what is necessary for
  // tabs.
  if (isset($variables['is_active']) && $variables['is_active'] === TRUE) {
    $variables['link']['#options']['attributes']['class'][] = 'active is-active';
  }
  else {
    $variables['link']['#options']['attributes']['class'][] = 'nav-link';
  }

  if (isset($variables['element']['#level'])) {
    $variables['level'] = $variables['element']['#level'];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vesta_bootstrap4_form_system_theme_settings_alter(&$form, FormStateInterface $form_state, $form_id = NULL) {
  // Work-around for a core bug affecting admin themes. See issue #943212.
  if (isset($form_id)) {
    return;
  }

  $options_theme = [
    'none' => 'do not apply theme',
    'light' => 'light (dark text/links against a light background)',
    'dark' => 'dark (light/white text/links against a dark background)',
  ];

  $options_colour = [
    'none' => 'do not apply colour',
    'primary' => 'primary',
    'secondary' => 'secondary',
    'light' => 'light',
    'dark' => 'dark',
  ];

  // Populating options for top container.
  $options_top_container = [
    'container' => 'fixed',
    'container-fluid m-0 p-0' => 'fluid',
  ];

  // Populating extra options for top container.
  foreach (explode("\n", theme_get_setting('b4_top_container_config') ?? '') as $line) {
    $values = explode("|", trim($line) ?? '');
    if (is_array($values) && (count($values) == 2)) {
      $options_top_container += [trim($values[0]) => trim($values[1])];
    }
  }

  $form['body_details'] = [
    '#type' => 'details',
    '#title' => t('Body options'),
    '#description' => t("Combination of theme/background colour may affect background colour/text colour contrast. To fix any contrast issues, override corresponding variables in scss(refer to dist/boostrap/scss/_variables.scss)"),
    '#open' => TRUE,
  ];

  $form['body_details']['b4_top_container'] = [
    '#type' => 'select',
    '#title' => t('Website container type'),
    '#default_value' => theme_get_setting('b4_top_container'),
    '#description' => t("Type of top level container: fluid (eg edge to edge) or fixed width"),
    '#options' => $options_top_container,
  ];

  $form['body_details']['b4_top_container_config'] = [
    '#type' => 'textarea',
    '#title' => t('Website container type configuration'),
    '#default_value' => theme_get_setting('b4_top_container_config'),
    '#description' => t("Format: <classes|label> on each line, e.g. <br><pre>container|fixed<br />container-fluid m-0 p-0|fluid</pre>"),
  ];

  $form['body_details']['b4_body_schema'] = [
    '#type' => 'select',
    '#title' => t('Body theme:'),
    '#default_value' => theme_get_setting('b4_body_schema'),
    '#description' => t("Text colour theme of the body."),
    '#options' => $options_theme,
  ];

  $form['body_details']['b4_body_bg_schema'] = [
    '#type' => 'select',
    '#title' => t('Body background:'),
    '#default_value' => theme_get_setting('b4_body_bg_schema'),
    '#description' => t("Background color of the body."),
    '#options' => $options_colour,
  ];

  $form['nav_details'] = [
    '#type' => 'details',
    '#title' => t('Navbar options'),
    '#description' => t("Combination of theme/background colour may affect background colour/text colour contrast. To fix any contrast issues, override \$navbar-light-*/\$navbar-dark-* variables (refer to dist/boostrap/scss/_variables.scss)"),
    '#open' => TRUE,
  ];

  $form['nav_details']['b4_navbar_schema'] = [
    '#type' => 'select',
    '#title' => t('Navbar theme:'),
    '#default_value' => theme_get_setting('b4_navbar_schema'),
    '#description' => t("Text colour theme of the navbar."),
    '#options' => $options_theme,
  ];

  $form['nav_details']['b4_navbar_bg_schema'] = [
    '#type' => 'select',
    '#title' => t('Navbar background:'),
    '#default_value' => theme_get_setting('b4_navbar_bg_schema'),
    '#description' => t("Background color of the navbar."),
    '#options' => $options_colour,
  ];

  $form['footer_details'] = [
    '#type' => 'details',
    '#title' => t('Footer options'),
    '#description' => t("Combination of theme/background colour may affect background colour/text colour contrast. To fix any contrast issues, override corresponding variables in scss (refer to dist/boostrap/scss/_variables.scss)"),
    '#open' => TRUE,
  ];

  $form['footer_details']['b4_footer_schema'] = [
    '#type' => 'select',
    '#title' => t('Footer theme:'),
    '#default_value' => theme_get_setting('b4_footer_schema'),
    '#description' => t("Text colour theme of the footer."),
    '#options' => $options_theme,
  ];

  $form['footer_details']['b4_footer_bg_schema'] = [
    '#type' => 'select',
    '#title' => t('Footer background:'),
    '#default_value' => theme_get_setting('b4_footer_bg_schema'),
    '#description' => t("Background color of the footer."),
    '#options' => $options_colour,
  ];

}

/**
 * Implements theme_preprocess_page().
 */
function vesta_bootstrap4_preprocess_page(&$variables) {
  // Pass variables to theme.
  $variables['b4_top_container'] = theme_get_setting('b4_top_container');
  // Navbar colour theme.
  $variables['b4_navbar_schema'] = theme_get_setting('b4_navbar_schema');
  $variables['b4_navbar_bg_schema'] = theme_get_setting('b4_navbar_bg_schema');
  // Footer colour theme.
  $variables['b4_footer_schema'] = theme_get_setting('b4_footer_schema');
  $variables['b4_footer_bg_schema'] = theme_get_setting('b4_footer_bg_schema');

}

/**
 * Implements theme_preprocess_textarea().
 */
function vesta_bootstrap4_preprocess_textarea(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

/**
 * Implements theme_preprocess_datetime_form().
 */
function vesta_bootstrap4_preprocess_datetime_form(&$variables) {
  $variables['attributes']['class'][] = 'form-inline';
}

/**
 * Implements theme_preprocess_html().
 */
function vesta_bootstrap4_preprocess_html(&$variables) {
  // Body colour theme.
  $variables['b4_body_schema'] = theme_get_setting('b4_body_schema');
  $variables['b4_body_bg_schema'] = theme_get_setting('b4_body_bg_schema');
}

/**
 * Implements theme_preprocess_table().
 */
function vesta_bootstrap4_preprocess_table(&$variables) {
  vesta_bootstrap4_covert_classes_string_to_array($variables);

  $variables['attributes']['class'][] = 'table';
  $variables['attributes']['class'][] = 'table-striped';
  $variables['attributes']['class'][] = 'table-hover';
}

/**
 * Implements theme_preprocess_views_ui_views_listing_table().
 */
function vesta_bootstrap4_preprocess_views_ui_views_listing_table(&$variables) {
  vesta_bootstrap4_preprocess_table($variables);
}

/**
 * Callback to mitigate when class is a string..
 */
function vesta_bootstrap4_covert_classes_string_to_array(&$variables) {
  if (isset($variables['attributes']['class']) && is_string($variables['attributes']['class'])) {
    $class = $variables['attributes']['class'];
    $variables['attributes']['class'] = [];
    $variables['attributes']['class'][] = $class;
  }
}

/**
 * Implements theme_preprocess_views_ui_display_tab_setting().
 */
function vesta_bootstrap4_preprocess_views_ui_display_tab_setting(&$variables) {
  vesta_bootstrap4_covert_classes_string_to_array($variables);
  $variables['attributes']['class'][] = 'my-1';
}

/**
 * Implements theme_preprocess_views_ui_display_tab_bucket().
 */
function vesta_bootstrap4_preprocess_views_ui_display_tab_bucket(&$variables) {
  vesta_bootstrap4_covert_classes_string_to_array($variables);
  $variables['attributes']['class'][] = 'my-2';
}
